### PR TITLE
Version bump to 3.0.7

### PR DESCRIPTION
**Pull request by robbavey**
Also adds changelog entry

### CODE REVIEW

**Comment by robbavey** [comment]
Thank you @karenzone!

**Comment by pemontto** [comment]
When should we expect this to be available with `logstash-plugin update`?

```shell
╰─ logstash --version
logstash 7.3.0
╰─ logstash-plugin list --verbose logstash-input-imap
logstash-input-imap (3.0.6)
╰─ logstash-plugin update logstash-input-imap
Updating logstash-input-imap
No plugin updated
```

**Comment by jsvd** [comment]
right now :) thanks for the reminder

**Comment by pemontto** [comment]
@jsvd and when will the docs get updated, looking at master and it's still v3.0.6?

https://www.elastic.co/guide/en/logstash/master/plugins-inputs-imap.html

**Pull request merged**
